import * as moment from 'moment';
export class Survey {
  id:any;
  sex:any;
  course:any;
  age:any;
  article1:any;
  article1_1:any;
  article1_2:any;
  article1_3:any;
  article1_4:any;
  article1_5:any;
  article1_6:any;
  article1_7:any;
  article1_8:any;
  article1_9:any;
  article1_10:any;
  article1_11:any;
  article1_12:any;
  article1_13:any;
  article1_14:any;
  article1_others:any;
  article2:any;
  article2_1:any;
  article2_2:any;
  article2_3:any;
  article2_4:any;
  article2_5:any;
  article2_6:any;
  article2_7:any;
  article2_8:any;
  article2_9:any;
  article2_10:any;
  article2_11:any;
  article2_12:any;
  article2_13:any;
  article2_14:any;
  article2_others:any;
  article3:any;
  article3_1:any;
  article3_2:any;
  article3_3:any;
  article3_4:any;
  article3_5:any;
  article3_6:any;
  article3_7:any;
  article3_8:any;
  article3_9:any;
  article3_10:any;
  article3_11:any;
  article3_12:any;
  article3_13:any;
  article3_14:any;
  article3_others:any;
  article4:any;
  article4_1:any;
  article4_2:any;
  article4_3:any;
  article4_4:any;
  article4_5:any;
  article4_6:any;
  article4_7:any;
  article4_8:any;
  article4_9:any;
  article4_10:any;
  article4_11:any;
  article4_12:any;
  article4_13:any;
  article4_14:any;
  article4_others:any;
  created_at:any;

  deserialize(input: any) {
    Object.assign(this, input);
    return this;
  }
  constructor(input:any = {
    id:null,
    sex:null,
    course:null,
    age:null,
    article1:false,
    article1_1:false,
    article1_2:false,
    article1_3:false,
    article1_4:false,
    article1_5:false,
    article1_6:false,
    article1_7:false,
    article1_8:false,
    article1_9:false,
    article1_10:false,
    article1_11:false,
    article1_12:false,
    article1_13:false,
    article1_14:false,
    article1_others:null,
    article2:false,
    article2_1:false,
    article2_2:false,
    article2_3:false,
    article2_4:false,
    article2_5:false,
    article2_6:false,
    article2_7:false,
    article2_8:false,
    article2_9:false,
    article2_10:false,
    article2_11:false,
    article2_12:false,
    article2_13:false,
    article2_14:false,
    article2_others:null,
    article3:false,
    article3_1:false,
    article3_2:false,
    article3_3:false,
    article3_4:false,
    article3_5:false,
    article3_6:false,
    article3_7:false,
    article3_8:false,
    article3_9:false,
    article3_10:false,
    article3_11:false,
    article3_12:false,
    article3_13:false,
    article3_14:false,
    article3_others:null,
    article4:false,
    article4_1:false,
    article4_2:false,
    article4_3:false,
    article4_4:false,
    article4_5:false,
    article4_6:false,
    article4_7:false,
    article4_8:false,
    article4_9:false,
    article4_10:false,
    article4_11:false,
    article4_12:false,
    article4_13:false,
    article4_14:false,
    article4_others:null,
    created_at: moment().format('YYYY-MM-DD HH:MM:SS')
  }){
      Object.assign(this, input);
  }

  toArray(){
    return [
      this.id,
      this.sex,
      this.course,
      this.age,
      this.article1,
      this.article1_1,
      this.article1_2,
      this.article1_3,
      this.article1_4,
      this.article1_5,
      this.article1_6,
      this.article1_7,
      this.article1_8,
      this.article1_9,
      this.article1_10,
      this.article1_11,
      this.article1_12,
      this.article1_13,
      this.article1_14,
      this.article1_others,
      this.article2,
      this.article2_1,
      this.article2_2,
      this.article2_3,
      this.article2_4,
      this.article2_5,
      this.article2_6,
      this.article2_7,
      this.article2_8,
      this.article2_9,
      this.article2_10,
      this.article2_11,
      this.article2_12,
      this.article2_13,
      this.article2_14,
      this.article2_others,
      this.article3,
      this.article3_1,
      this.article3_2,
      this.article3_3,
      this.article3_4,
      this.article3_5,
      this.article3_6,
      this.article3_7,
      this.article3_8,
      this.article3_9,
      this.article3_10,
      this.article3_11,
      this.article3_12,
      this.article3_13,
      this.article3_14,
      this.article3_others,
      this.article4,
      this.article4_1,
      this.article4_2,
      this.article4_3,
      this.article4_4,
      this.article4_5,
      this.article4_6,
      this.article4_7,
      this.article4_8,
      this.article4_9,
      this.article4_10,
      this.article4_11,
      this.article4_12,
      this.article4_13,
      this.article4_14,
      this.article4_others
    ];
  }
}
